'use strict';

const KEY='ecocode_final_v2';

const scenarios=[
  {id:'camp',title:'Поход с друзьями',icon:'⛺',meta:'уровень 1 · 7 решений',desc:'Ты отвечаешь за решения группы: сначала разведка места, затем — контроль риска.',mood:'sunset',objective:'Научиться замечать риск до того, как появляется огонь.',lesson:'Ключевая идея: безопасное решение начинается не с костра, а с оценки места, погоды и действующих ограничений.',hotspots:[['bag','Рюкзак'],['fire','Место'],['sky','Погода']],questions:[
['РАЗВЕДКА','Вы пришли на стоянку. Первые две минуты лучше потратить на…',[['поиск самого сухого участка','wrong','Сухая растительность рядом с местом отдыха — дополнительный риск.'],['оценку места, погоды и действующих ограничений','correct','Верно. До любого решения с огнём нужно понять, безопасен ли формат отдыха сегодня.'],['подготовку дров, чтобы не терять время','wrong','Сначала условия, потом действия. Заготовка дров не должна опережать оценку риска.']]],
['УСЛОВИЯ','Ветер усиливается, а вокруг много сухой травы. Компания говорит: «Но огонь будет маленьким». Твой ответ?',[['Размер огня не отменяет риск: от открытого огня лучше отказаться','correct','Именно. МЧС ЯНАО отдельно указывает, что костёр нельзя разводить в ветреную погоду и рядом с сухой растительностью.'],['Можно, если поставить огонь между людьми','wrong','Люди рядом не делают источник огня безопаснее.'],['Можно, если быстро закончить','wrong','Скорость не компенсирует опасные условия.']]],
['ПРАВИЛО','На табличке у стоянки указано временное ограничение на использование открытого огня. Что меняется?',[['Ничего: правило действует только для больших костров','wrong','Ограничение нужно соблюдать независимо от размера предполагаемого огня.'],['План отдыха меняется: выбираем вариант без открытого огня','correct','Да. Действующие ограничения важнее привычного сценария отдыха.'],['Можно спросить друзей, насколько строго его соблюдают','wrong','Правило не зависит от мнения компании.']]],
['РЕШЕНИЕ ГРУППЫ','Друг предлагает оставить рядом с местом отдыха бутылку, тряпку с масляным пятном и спички «на потом». Что ты убираешь первым?',[['Только бутылку','wrong','Опасными могут быть разные источники воспламенения.'],['Все потенциально опасные материалы и источники огня','correct','Верно. МЧС ЯНАО отдельно предупреждает о горючих материалах и стекле на солнечных полянах.'],['Ничего: пока огня нет, риска нет','wrong','Риск существует ещё до появления пламени.']]],
['НЕОЖИДАННО','Из леса доносится запах дыма. Ты не видишь пламени. Что делает группа?',[['Идёт искать источник дыма','wrong','Приближаться к возможному пожару не нужно.'],['Останавливается, сообщает взрослым и передаёт информацию по 101 или 112','correct','Да. При обнаружении возгорания МЧС ЯНАО рекомендует незамедлительно сообщать по 101 или 112.'],['Снимает видео и ждёт, пока станет понятнее','wrong','Сначала безопасность и сообщение о возможном пожаре.']]],
['ФИНАЛ','Какое решение показывает настоящий навык туриста?',[['«Я умею разжечь костёр»','wrong','Туристический навык — не создавать лишний риск.'],['«Я умею остановить небезопасный план, даже если друзьям он нравится»','correct','Это и есть ответственное решение: замечать риск и менять план.'],['«Я делаю как большинство»','wrong','Безопасность не определяется голосованием компании.']]],
['ПРОВЕРКА','Перед уходом группа обсуждает: «Если огня не видно, значит всё нормально». Что ответишь?',[['Да, можно уходить сразу','wrong','Отсутствие видимого пламени не доказывает отсутствие опасности.'],['Нет: место нужно оставить без источников огня и опасных материалов','correct','Верно. Уход — это часть ответственности за место отдыха.'],['Главное — не оставить еду','wrong','Еда не является главным критерием пожарной безопасности.']]]]},
  {id:'fish',title:'Рыбалка в тундре',icon:'◒',meta:'уровень 2 · 7 решений',desc:'Погода меняется, видимость ухудшается, а привычный план перестаёт быть безопасным.',mood:'storm',objective:'Учиться перестраивать план, когда условия меняются.',lesson:'Ключевая идея: прогноз и ограничения — часть экипировки. Если условия ухудшаются, безопасный вариант может быть совсем без огня.',hotspots:[['bag','Снаряжение'],['fire','Стоянка'],['sky','Небо']],questions:[
['ПЛАН','Перед выездом ты проверяешь прогноз. Что важно смотреть кроме температуры?',[['только вероятность дождя','wrong','Одного показателя недостаточно для оценки обстановки.'],['предупреждения, погодные условия и действующие ограничения','correct','Верно. Решение о формате отдыха зависит от всей обстановки.'],['только время заката','wrong','Время суток важно, но не заменяет оценку пожарной обстановки.']]],
['СНАРЯЖЕНИЕ','В группе предлагают взять горючую жидкость «для быстрого розжига». Твоя реакция?',[['согласиться, если её совсем немного','wrong','Горючие жидкости не превращают отдых в безопасный сценарий.'],['отказаться от идеи и выбрать безопасный способ организации отдыха','correct','Да. МЧС ЯНАО прямо предупреждает против использования горючих смесей при разведении костров.'],['проверить, насколько быстро она горит','wrong','Экспериментировать с огнём нельзя.']]],
['ВЕТЕР','Через час ветер становится заметно сильнее. Почему это не «мелочь»?',[['Потому что ветер может способствовать распространению огня','correct','Верно. Поэтому в ветреную погоду от открытого огня нужно отказаться.'],['Потому что будет холоднее','wrong','Температура может быть важна, но здесь главный вопрос — пожарный риск.'],['Потому что рыба перестанет клевать','wrong','Это не причина пожарного риска.']]],
['НАБЛЮДЕНИЕ','Вдалеке появился дым. Что является плохой идеей?',[['остаться на безопасном расстоянии','wrong','Сама дистанция — не проблема.'],['сообщить взрослым и экстренным службам при необходимости','wrong','Это правильное действие.'],['идти к дыму, чтобы «точно узнать, что случилось»','correct','Именно так делать не стоит: к потенциальному источнику пожара приближаться опасно.']]],
['КОММУНИКАЦИЯ','Если сообщаешь о пожаре по 101 или 112, какая информация особенно полезна?',[['только своё имя','wrong','Диспетчеру нужна информация, помогающая определить место и ситуацию.'],['место или ближайший ориентир и что именно ты видишь','correct','Верно. Важно спокойно описать место, характер ситуации и угрозу людям.'],['только фотография','wrong','Фото не заменяет голосовое сообщение о месте и обстановке.']]],
['ПОВОРОТ ПЛАНА','Компания уже собрала лагерь, но условия стали небезопасными. Что сложнее всего сделать правильно?',[['признать, что первоначальный план больше не подходит','correct','Это важный навык: безопасное решение иногда означает отказаться от уже подготовленного плана.'],['продолжить, чтобы не потерять время','wrong','Потерянное время не важнее безопасности.'],['спросить, кто из друзей готов рискнуть','wrong','Безопасность не определяется готовностью рисковать.']]],
['ФИНАЛ','Какой принцип подходит для любой поездки на природу?',[['«План нельзя менять»','wrong','План должен меняться вместе с условиями.'],['«Сначала условия и последствия, потом действие»','correct','Это главный принцип «ЭкоКода».'],['«Если раньше получалось, значит и сейчас можно»','wrong','Условия могут измениться.']]]]},
  {id:'picnic',title:'Семейный пикник',icon:'▱',meta:'уровень 3 · 7 решений',desc:'Здесь важно не только знать правило, но и суметь объяснить его другим.',mood:'picnic',objective:'Научиться защищать безопасное решение в реальной компании.',lesson:'Ключевая идея: ответственность — это не «самый смелый» поступок, а способность вовремя остановить риск и позвать взрослого.',hotspots:[['bag','Вещи'],['fire','Поляна'],['sky','Обстановка']],questions:[
['ПОДГОТОВКА','Семья выбирает место для отдыха. Какой вопрос должен появиться до обсуждения костра?',[['«Где удобнее поставить мангал?»','wrong','Сначала нужно понять, разрешён ли открытый огонь и безопасно ли место.'],['«Какие здесь правила и какие ограничения действуют сегодня?»','correct','Да. Правила и текущая обстановка определяют формат отдыха.'],['«Кто быстрее принесёт дрова?»','wrong','Заготовка топлива не должна быть первым решением.']]],
['МЕСТО','На поляне сухая трава, а рядом низкие ветви. Кто-то говорит: «Просто отодвинем траву». Что отвечаешь?',[['Этого недостаточно: при таких условиях лучше отказаться от открытого огня','correct','Верно. МЧС ЯНАО запрещает разводить костёр в местах с сухой травой и под низко свисающими кронами.'],['Можно, если огонь будет маленьким','wrong','Маленький огонь не отменяет опасных условий.'],['Можно, если рядом будет взрослый','wrong','Присутствие взрослого не отменяет запрет или опасные условия.']]],
['ДЕТИ','Младшие дети начинают бегать между местом отдыха и вещами. Какое решение лучше?',[['ничего не менять','wrong','Безопасность пространства нужно организовать заранее.'],['убрать потенциально опасные предметы и передать контроль взрослым','correct','Да. Ребёнок не должен становиться «контролёром огня» или источника риска.'],['назначить ребёнка ответственным за порядок','wrong','Ответственность за безопасность должна оставаться у взрослых.']]],
['ОБЪЕКТ','На солнце лежит стеклянная бутылка. Почему её не стоит оставлять?',[['она может сфокусировать солнечный свет на сухой растительности','correct','МЧС ЯНАО отдельно предупреждает не оставлять стекло на солнечных полянах.'],['потому что стекло всегда взрывается на солнце','wrong','Так утверждать нельзя. Риск связан с возможным фокусированием солнечного света.'],['потому что бутылка мешает фотографироваться','wrong','Причина здесь связана с пожарной безопасностью.']]],
['ДЫМ','Появился дым, и взрослый говорит: «Наверное, это просто туман». Как действуешь?',[['соглашаюсь и продолжаю пикник','wrong','Неизвестный дым нельзя игнорировать.'],['сообщаю о дыме взрослым и при необходимости — по 101 или 112','correct','Верно. При обнаружении возгорания важно своевременно сообщить.'],['сам иду проверять источник','wrong','К потенциальному пожару приближаться не следует.']]],
['ВЛИЯНИЕ','Друг говорит: «Не хочу выглядеть паникёром». Что ответить?',[['«Тогда ничего не делаем»','wrong','Страх показаться неудобным не должен отменять безопасность.'],['«Осторожность — это не паника. Мы проверяем ситуацию и действуем по правилам»','correct','Точно. Ответственное поведение может быть спокойным и уверенным.'],['«Давай спорить, кто прав»','wrong','В экстренной ситуации важнее безопасное действие, а не спор.']]],
['ФИНАЛ','Что отличает знание правила от настоящего навыка?',[['я могу повторить правило','wrong','Это только первый уровень.'],['я замечаю риск, объясняю его и меняю решение группы','correct','Именно такой перенос знания в действие и тренирует симулятор.'],['я запоминаю больше телефонов','wrong','Телефоны важны, но навык шире: заметить риск и действовать правильно.']]]]},
];

const state={name:'',xp:0,done:{},streak:0,best:0};
let current=null,qIndex=0,risk=0,sessionXP=0,safe=0,hotspots=new Set(),actionUsed={};
const $=id=>document.getElementById(id);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object'){state.name=typeof x.name==='string'?x.name.slice(0,24):'';state.xp=Number.isFinite(x.xp)?Math.max(0,x.xp):0;state.done=x.done&&typeof x.done==='object'?x.done:{};state.streak=Number.isFinite(x.streak)?Math.max(0,x.streak):0;state.best=Number.isFinite(x.best)?Math.max(0,x.best):0;}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='sim')renderScenarios();if(id==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'})}
function updateHeader(){const n=state.name||'Гость';$('profileName').textContent=n;if($('homeGreeting'))$('homeGreeting').textContent=n?`С возвращением, ${n}. Прогресс хранится только в этом браузере.`:'Имя и игровой прогресс хранятся только на этом устройстве.';if($('progressTitle'))$('progressTitle').textContent=n?`${n}, твой прогресс`:'Твой прогресс'}
function openProfile(){$('nameInput').value=state.name;$('profileModal').classList.add('show');setTimeout(()=>$('nameInput').focus(),30)}
function closeProfile(){$('profileModal').classList.remove('show')}
function saveProfile(){state.name=$('nameInput').value.trim().replace(/\s+/g,' ').slice(0,24);save();updateHeader();closeProfile();toast(state.name?`Готово, ${state.name}.`:'Профиль очищен.')}
function ensureGameUI(){const game=$('game'),scene=$('scene');if(!$('briefing')){const b=document.createElement('div');b.id='briefing';b.className='briefing';b.setAttribute('aria-live','polite');game.insertBefore(b,game.querySelector('.scene-wrap'));}if(!$('hotspots')){const h=document.createElement('div');h.id='hotspots';h.className='hotspots';scene.append(h)}if(!$('scene-visual')){const v=document.createElement('div');v.id='scene-visual';v.className='scene-visual';v.setAttribute('aria-hidden','true');v.innerHTML='<div class="scene-sky"></div><div class="scene-ground"></div><div class="scene-trees"></div><div class="scene-lake"></div><div class="scene-cloud"></div><div class="scene-rain"></div><div class="scene-wind"></div><div class="scene-tent"></div><div class="scene-fire"></div><div class="scene-person"></div><div class="scene-blanket"></div><div class="scene-basket"></div>';scene.prepend(v)}const oldWater=$('waterBtn');if(oldWater){oldWater.id='leaveBtn';oldWater.textContent='↩️ Уйти от риска'}const oldCall=$('callBtn');if(oldCall)oldCall.textContent='📞 Сообщить 101/112'}
function renderScenarios(){const list=$('scenarioList');list.replaceChildren();scenarios.forEach((s,i)=>{const unlocked=i===0||!!state.done[scenarios[i-1].id];const card=document.createElement('article');card.className='scenario-card '+s.mood+(unlocked?'':' locked');card.tabIndex=unlocked?0:-1;card.setAttribute('role','button');const icon=document.createElement('div');icon.className='sc-icon';icon.textContent=s.icon;const body=document.createElement('div');const title=document.createElement('div');title.className='sc-title';title.textContent=s.title;const desc=document.createElement('div');desc.className='sc-desc';desc.textContent=s.desc;const meta=document.createElement('div');meta.className='sc-meta';meta.textContent=s.meta+' · наблюдение + решения';body.append(title,desc,meta);const status=document.createElement('span');status.className='status '+(state.done[s.id]?'done':unlocked?'open':'');status.textContent=state.done[s.id]?'✓ пройден':unlocked?'играть':'закрыт';card.append(icon,body,status);if(unlocked){card.addEventListener('click',()=>start(s.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();start(s.id)}})}list.append(card)});const done=scenarios.filter(s=>state.done[s.id]).length;$('overallProgressText').textContent=`${done} / ${scenarios.length}`;$('overallProgressBar').style.width=`${done/scenarios.length*100}%`}
function start(id){current=scenarios.find(s=>s.id===id);if(!current)return;qIndex=0;risk=0;sessionXP=0;safe=0;hotspots=new Set();actionUsed={};$('game').hidden=false;$('questionBox').style.display='block';$('result').classList.remove('show');ensureGameUI();$('gameTitle').textContent=current.title;$('gameStep').textContent=`Решение 1 из ${current.questions.length}`;$('scene').className='scene '+current.mood;renderBriefing();renderHotspots();renderQuestion();updateScene();setTimeout(()=>$('game').scrollIntoView({behavior:'smooth',block:'start'}),30)}
function renderBriefing(){const b=$('briefing');b.innerHTML='';const a=document.createElement('div');a.className='brief-item';a.innerHTML='<span>МИССИЯ</span><strong></strong>';a.querySelector('strong').textContent=current.objective;const c=document.createElement('div');c.className='brief-item';c.innerHTML='<span>ЗНАНИЕ</span><strong></strong>';c.querySelector('strong').textContent=current.lesson;b.append(a,c);b.classList.add('show')}
function renderHotspots(){const box=$('hotspots');box.replaceChildren();current.hotspots.forEach(([type,label],i)=>{const b=document.createElement('button');b.className='hotspot spot-'+type;b.type='button';b.textContent=(i===0?'◉ ':i===1?'◇ ':'△ ')+label;b.addEventListener('click',()=>inspect(type));box.append(b)})}
function renderQuestion(){const q=current.questions[qIndex];$('gameStep').textContent=`Решение ${qIndex+1} из ${current.questions.length}`;$('questionTag').textContent=q[0];$('questionCount').textContent=`${qIndex+1} / ${current.questions.length}`;$('questionText').textContent=q[1];const box=$('answers');box.replaceChildren();q[2].forEach(x=>{const b=document.createElement('button');b.className='answer';b.type='button';b.textContent=x[0];b.addEventListener('click',()=>answer(b,x[1],x[2]));box.append(b)});$('feedback').className='feedback';$('feedback').textContent='';['leaveBtn','adultBtn','callBtn'].forEach(id=>$(id).disabled=false)}
function answer(btn,kind,feedback){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const ok=kind==='correct';btn.classList.add(ok?'correct':'wrong');const f=$('feedback');f.replaceChildren();const b=document.createElement('b');b.textContent=ok?'Решение засчитано. ':'Разберём последствия. ';f.append(b,document.createTextNode(feedback));f.classList.add('show');if(ok){risk=Math.max(0,risk-6);sessionXP+=30;safe++;state.streak++;state.best=Math.max(state.best,state.streak)}else{risk=Math.min(100,risk+16);sessionXP+=6;state.streak=0}state.xp+=ok?30:6;save();updateScene();setTimeout(()=>{if(qIndex<current.questions.length-1){qIndex++;renderQuestion()}else finish()},1000)}
function finish(){state.done[current.id]=true;save();$('questionBox').style.display='none';$('result').classList.add('show');$('resultXP').textContent=sessionXP;$('resultRisk').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('resultDecisions').textContent=`${safe}/${current.questions.length}`;$('resultTitle').textContent=risk<25?'Ты управлял риском':risk<55?'Ты заметил не всё':'Риск вырос из-за решений';$('resultText').textContent=risk<25?'Сильный результат: ты не просто знал правила, а менял план, когда условия становились опасными.':risk<55?'Есть база. Повтори сценарий и попробуй заметить риск на один шаг раньше.':'Главный вывод: в безопасности важнее вовремя остановить небезопасный план, чем довести его до конца.';renderScenarios();renderProgress()}
function updateScene(){$('riskMeter').style.width=risk+'%';$('riskLabel').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('gameXP').textContent=sessionXP;$('scene').style.setProperty('--risk',risk);$('scene').dataset.risk=risk<25?'safe':risk<55?'watch':'danger'}
function inspect(type){if(hotspots.has(type))return;hotspots.add(type);const msg={bag:'Проверь снаряжение: никакие горючие жидкости и случайные источники огня не должны становиться частью плана.',fire:'Осмотри место: сухая растительность, низкие ветви и ветер — повод отказаться от открытого огня.',sky:'Проверь обстановку: погода, предупреждения и действующие ограничения могут изменить весь план.'};toast(msg[type]);const b=document.querySelector('.spot-'+type);if(b)b.classList.add('used');sessionXP+=5;$('gameXP').textContent=sessionXP}
function mini(type){if(actionUsed[type])return;actionUsed[type]=true;if(type==='leave'){risk=Math.max(0,risk-14);toast('Ты выбрал безопасный выход из рискованной ситуации.')}if(type==='adult'){risk=Math.max(0,risk-10);toast('Хороший шаг: подключить взрослого и не решать опасную ситуацию в одиночку.')}if(type==='call'){risk=0;toast('При пожаре сообщают по 101 или 112. Не приближайся к очагу.')}const id=type==='leave'?'leaveBtn':type==='adult'?'adultBtn':'callBtn';$(id).disabled=true;updateScene()}
function renderProgress(){const done=scenarios.filter(s=>state.done[s.id]).length;$('totalXP').textContent=state.xp+' XP';$('doneCount').textContent=`${done} / ${scenarios.length}`;$('safeStreak').textContent=state.best;const badges=[['🌱','Первый шаг','Пройден 1 сценарий',done>=1],['🧭','Смена плана','Пройдены 2 сценария',done>=2],['✦','ЭкоКод','Пройдены все сценарии',done>=3],['⚡','Холодная голова','5 безопасных решений подряд',state.best>=5]];const wrap=$('badges');wrap.replaceChildren();badges.forEach(b=>{const x=document.createElement('article');x.className='badge'+(b[3]?'':' locked');const m=document.createElement('div');m.className='medal';m.textContent=b[0];const t=document.createElement('strong');t.textContent=b[1];const d=document.createElement('span');d.textContent=b[2];x.append(m,t,d);wrap.append(x)})}
function reset(){if(!window.confirm('Сбросить имя и игровой прогресс на этом устройстве?'))return;try{localStorage.removeItem(KEY);localStorage.removeItem('ecocode_final_v1')}catch(e){}location.reload()}
function bind(){ensureGameUI();document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();view(v.dataset.view)}const a=e.target.closest('[data-action]');if(a){e.preventDefault();if(a.dataset.action==='start'){view('sim');setTimeout(()=>start(scenarios.find(s=>!state.done[s.id])?.id||scenarios[0].id),120)}else if(a.dataset.action==='how'){document.querySelector('#view-home .section').scrollIntoView({behavior:'smooth'})}else if(a.dataset.action==='profile')openProfile();else if(a.dataset.action==='reset')reset()}});$('profileBtn').addEventListener('click',openProfile);$('closeModal').addEventListener('click',closeProfile);$('saveName').addEventListener('click',saveProfile);$('nameInput').addEventListener('keydown',e=>{if(e.key==='Enter')saveProfile()});$('profileModal').addEventListener('click',e=>{if(e.target===$('profileModal'))closeProfile()});$('leaveBtn').addEventListener('click',()=>mini('leave'));$('adultBtn').addEventListener('click',()=>mini('adult'));$('callBtn').addEventListener('click',()=>mini('call'));$('replayBtn').addEventListener('click',()=>{if(current)start(current.id)});$('backBtn').addEventListener('click',()=>{$('game').hidden=true;$('result').classList.remove('show');view('sim')})}
load();bind();updateHeader();renderScenarios();renderProgress();
