'use strict';
const KEY='ecocode_final_v1';
const scenarios=[
{id:'camp',title:'Поход с друзьями',desc:'Собираетесь на стоянку. Нужно решить, как организовать отдых без лишнего риска.',icon:'⛺',meta:'уровень 1 · около 5 мин',questions:[
['НАБЛЮДЕНИЕ','Вы пришли на место. С чего начать?',[['Сразу разжечь костёр','wrong','Сначала нужно оценить условия и убедиться, что открытый огонь здесь вообще допустим.'],['Проверить правила и условия на сегодня','correct','Верно. Ограничения могут меняться из-за пожароопасной обстановки.'],['Пойти искать самое сухое место','wrong','Сухая растительность — дополнительный риск, а не преимущество.']]],
['РЮКЗАК','В рюкзаке есть спички. Что важно сделать?',[['Оставить их рядом с местом отдыха','wrong','Источник огня не должен становиться случайной опасностью.'],['Убрать так, чтобы они не стали случайным источником огня','correct','Верно. Главное — не создавать лишний риск.'],['Проверить спички, поджигая одну','wrong','Экспериментировать с огнём на природе нельзя.']]],
['МЕСТО','Рядом сухая трава, а ветер усиливается. Что выбираешь?',[['Продолжить как обычно','wrong','Условия стали менее безопасными. Риск нужно снижать, а не игнорировать.'],['Отказаться от открытого огня и выбрать безопасный вариант отдыха','correct','Да. Ветер и сухая растительность повышают опасность распространения огня.'],['Поставить костёр ближе к сухой траве','wrong','Это повышает риск распространения огня.']]],
['СИТУАЦИЯ','Ты заметил опасное возгорание неподалёку. Твой первый шаг?',[['Подойти ближе, чтобы рассмотреть','wrong','К опасному возгоранию приближаться не нужно.'],['Сообщить взрослым и при необходимости позвонить 101 или 112','correct','Верно. При обнаружении возгорания сообщают по 101 или 112.'],['Снять видео и подождать','wrong','Сначала безопасность и сообщение о возгорании.']]],
['ФИНАЛ','Перед уходом со стоянки что важнее всего?',[['Проверить только рюкзак','wrong','Нужно убедиться, что после отдыха не осталось источника опасности.'],['Убедиться, что место оставлено безопасным и без источников огня','correct','Да. Безопасность важнее скорости ухода.'],['Оставить всё как есть, если огня не видно','wrong','Нельзя исходить только из того, что огня не видно.']]]]},
{id:'fish',title:'Рыбалка в тундре',desc:'Ветер меняется, погода портится. Учись замечать риск до того, как он станет проблемой.',icon:'◌',meta:'уровень 2 · около 5 мин',questions:[
['ПОГОДА','Перед выходом погода выглядит сухой и ветреной. Что учитываешь?',[['Только температуру','wrong','Для пожарной безопасности важны не только ощущения от температуры.'],['Официальные предупреждения и местные ограничения','correct','Верно. Условия и ограничения нужно проверять перед отдыхом.'],['Ничего, ведь дождя сейчас нет','wrong','Отсутствие дождя само по себе не делает ситуацию безопасной.']]],
['ОТДЫХ','Компания хочет использовать открытый огонь. Что делаешь?',[['Проверяю, разрешён ли он сейчас и здесь','correct','Да. Правила зависят от действующих ограничений и обстановки.'],['Разрешаю, если огонь маленький','wrong','Размер огня не отменяет действующие ограничения.'],['Выбираю место рядом с сухой растительностью','wrong','Сухая растительность увеличивает риск.']]],
['ВЕТЕР','Ветер заметно усилился. Самое разумное решение?',[['Сделать огонь выше','wrong','Усиление ветра — причина снижать риск.'],['Отказаться от открытого огня','correct','Верно. Это простое решение снижает риск.'],['Перенести огонь ближе к палатке','wrong','Так делать опаснее, а не безопаснее.']]],
['СООБЩЕНИЕ','Увидел дым от природного пожара. Что делать?',[['Подойти и проверить','wrong','Приближаться к опасному пожару не нужно.'],['Сообщить взрослым и позвонить 101 или 112','correct','Верно. При обнаружении возгорания сообщают по 101 или 112.'],['Ничего, если дым далеко','wrong','Даже удалённое возгорание важно передать взрослым и службам.']]],
['ФИНАЛ','Какой принцип забираешь с собой?',[['Сначала скорость','wrong','Безопасность начинается с оценки ситуации.'],['Сначала условия и последствия, потом действие','correct','Именно так работает ответственное поведение на природе.'],['Сначала эксперимент','wrong','Открытый огонь не место для экспериментов.']]]]},
{id:'picnic',title:'Семейный пикник',desc:'Нужно выбрать безопасный формат отдыха и заметить признаки меняющейся обстановки.',icon:'✦',meta:'уровень 3 · около 5 мин',questions:[
['ПЛАН','Семья собирается на природу. Что проверяете заранее?',[['Только список еды','wrong','Для безопасного отдыха важны ещё правила и обстановка.'],['Правила места и актуальные ограничения','correct','Верно. Ограничения могут вводиться при высокой пожарной опасности.'],['Только заряд телефона','wrong','Заряд полезен, но не заменяет оценку условий.']]],
['МЕСТО','Вы нашли сухую траву и думаете о костре. Решение?',[['Не использовать открытый огонь','correct','Да. Сухая растительность — лишний риск.'],['Развести небольшой костёр','wrong','Маленький огонь всё равно может стать источником пожара.'],['Проверить ветер, бросив траву в огонь','wrong','Эксперименты с огнём не нужны.']]],
['ДЕТИ','Младшие дети играют рядом с местом отдыха. Что меняешь?',[['Оставляю всё как есть','wrong','Нужно организовать пространство безопаснее.'],['Убираю потенциальные источники опасности и держу детей под присмотром взрослых','correct','Верно. Безопасная организация пространства важна не меньше правил.'],['Предлагаю детям самим следить за огнём','wrong','Ответственность за безопасность должна оставаться у взрослых.']]],
['ДЫМ','Появился дым вдалеке. Что делать?',[['Игнорировать','wrong','Дым может быть признаком природного пожара.'],['Сообщить взрослым и при необходимости в 101/112','correct','Верно. При обнаружении возгорания сообщают по 101 или 112.'],['Идти навстречу дыму','wrong','К источнику опасности приближаться не следует.']]],
['ФИНАЛ','Как выглядит хороший туристический навык?',[['Уметь быстро разжечь огонь','wrong','Навык ответственного туриста — не создавать лишнего риска.'],['Уметь заметить риск и вовремя выбрать безопасное решение','correct','Да. Именно это тренирует ЭкоКод.'],['Уметь скрыть следы отдыха','wrong','Главное — безопасно организовать отдых и не оставлять источников опасности.']]]]},
];
const state={name:'',xp:0,done:{},streak:0};let current=null,qIndex=0,risk=0,sessionXP=0,safe=0,hotspots=new Set(),actionUsed={};
const $=id=>document.getElementById(id);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object'){state.name=typeof x.name==='string'?x.name.slice(0,24):'';state.xp=Number.isFinite(x.xp)?Math.max(0,x.xp):0;state.done=x.done&&typeof x.done==='object'?x.done:{};state.streak=Number.isFinite(x.streak)?Math.max(0,x.streak):0;}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='sim')renderScenarios();if(id==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'})}
function updateHeader(){const n=state.name||'Гость';$('profileName').textContent=n;$('homeGreeting').textContent=n?`С возвращением, ${n}. Имя и игровой прогресс хранятся только в этом браузере.`:'Сохраняем только имя/ник и игровой прогресс на этом устройстве.';$('progressTitle').textContent=n?`${n}, твой прогресс`:'Твой прогресс'}
function openProfile(){$('nameInput').value=state.name;$('profileModal').classList.add('show');setTimeout(()=>$('nameInput').focus(),30)}
function closeProfile(){$('profileModal').classList.remove('show')}
function saveProfile(){state.name=$('nameInput').value.trim().replace(/\s+/g,' ').slice(0,24);save();updateHeader();closeProfile();toast(state.name?`Готово, ${state.name}.`:'Профиль очищен.');}
function start(id){current=scenarios.find(s=>s.id===id);if(!current)return;qIndex=0;risk=0;sessionXP=0;safe=0;hotspots=new Set();actionUsed={};$('game').hidden=false;$('questionBox').style.display='block';$('result').classList.remove('show');$('gameTitle').textContent=current.title;renderQuestion();updateScene();setTimeout(()=>$('game').scrollIntoView({behavior:'smooth',block:'start'}),30)}
function renderScenarios(){const list=$('scenarioList');list.replaceChildren();scenarios.forEach((s,i)=>{const unlocked=i===0||!!state.done[scenarios[i-1].id];const card=document.createElement('article');card.className='scenario-card'+(unlocked?'':' locked');card.tabIndex=unlocked?0:-1;card.setAttribute('role','button');const icon=document.createElement('div');icon.className='sc-icon';icon.textContent=s.icon;const body=document.createElement('div');const title=document.createElement('div');title.className='sc-title';title.textContent=s.title;const desc=document.createElement('div');desc.className='sc-desc';desc.textContent=s.desc;const meta=document.createElement('div');meta.className='sc-meta';meta.textContent=s.meta+' · 5 решений';body.append(title,desc,meta);const status=document.createElement('span');status.className='status '+(state.done[s.id]?'done':unlocked?'open':'');status.textContent=state.done[s.id]?'✓ пройден':unlocked?'играть':'закрыт';card.append(icon,body,status);if(unlocked){card.addEventListener('click',()=>start(s.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();start(s.id)}})}list.append(card)});const done=scenarios.filter(s=>state.done[s.id]).length;$('overallProgressText').textContent=`${done} / ${scenarios.length}`;$('overallProgressBar').style.width=`${done/scenarios.length*100}%`}
function renderQuestion(){const q=current.questions[qIndex];$('gameStep').textContent=`Решение ${qIndex+1} из ${current.questions.length}`;$('questionTag').textContent=q[0];$('questionCount').textContent=`${qIndex+1} / ${current.questions.length}`;$('questionText').textContent=q[1];const box=$('answers');box.replaceChildren();q[2].forEach(x=>{const b=document.createElement('button');b.className='answer';b.type='button';b.textContent=x[0];b.addEventListener('click',()=>answer(b,x[1],x[2]));box.append(b)});$('feedback').className='feedback';$('feedback').textContent='';['waterBtn','adultBtn','callBtn'].forEach(id=>$(id).disabled=false)}
function answer(btn,kind,feedback){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const ok=kind==='correct';btn.classList.add(ok?'correct':'wrong');const f=$('feedback');f.replaceChildren();const b=document.createElement('b');b.textContent=ok?'Правильный выбор. ':'Разберём выбор. ';f.append(b,document.createTextNode(feedback));f.classList.add('show');if(ok){risk=Math.max(0,risk-8);sessionXP+=25;safe++;state.streak++}else{risk=Math.min(100,risk+18);sessionXP+=5;state.streak=0}state.xp+=ok?25:5;save();updateScene();setTimeout(()=>{if(qIndex<current.questions.length-1){qIndex++;renderQuestion()}else finish()},850)}
function finish(){state.done[current.id]=true;save();$('questionBox').style.display='none';$('result').classList.add('show');$('resultXP').textContent=sessionXP;$('resultRisk').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('resultDecisions').textContent=`${safe}/5`;$('resultTitle').textContent=risk<25?'Маршрут под контролем':risk<55?'Ты заметил часть риска':'Риск оказался высоким';$('resultText').textContent=risk<25?'Отлично: ты несколько раз выбрал решение, которое снижает риск.':risk<55?'Хорошая попытка. Повтори сценарий и посмотри, где можно было раньше заметить опасность.':'Главный вывод: безопасность начинается ещё до того, как появляется опасная ситуация.';renderScenarios();renderProgress()}
function updateScene(){$('riskMeter').style.width=risk+'%';$('riskLabel').textContent=risk<25?'низкий':risk<55?'средний':'высокий';$('gameXP').textContent=sessionXP}
function inspect(type){if(hotspots.has(type))return;hotspots.add(type);const msg={bag:'В рюкзаке нет «магического» безопасного огня: лучший инструмент — заранее проверить правила.',fire:'Сухая растительность и ветер — повод отказаться от открытого огня.',sky:'Перед отдыхом важно учитывать официальные предупреждения и действующие ограничения.'};toast(msg[type]);const ids={bag:'spotBag',fire:'spotFire',sky:'spotSky'};$(ids[type]).classList.add('used');sessionXP+=5;$('gameXP').textContent=sessionXP}
function mini(type){if(actionUsed[type])return;actionUsed[type]=true;if(type==='water'){risk=Math.max(0,risk-12);toast('Риск снижен: ты выбрал безопасное действие.')}if(type==='adult'){risk=Math.max(0,risk-8);toast('Хороший шаг: взрослый помогает оценить ситуацию.')}if(type==='call'){risk=0;toast('При опасном возгорании сообщают по 101 или 112. Не приближайся к огню.')}$(type==='water'?'waterBtn':type==='adult'?'adultBtn':'callBtn').disabled=true;updateScene()}
function renderProgress(){const done=scenarios.filter(s=>state.done[s.id]).length;$('totalXP').textContent=state.xp+' XP';$('doneCount').textContent=`${done} / ${scenarios.length}`;$('safeStreak').textContent=state.streak;const badges=[['🌱','Первый шаг','Пройден 1 сценарий',done>=1],['🧭','Осторожный маршрут','Пройдено 2 сценария',done>=2],['✦','ЭкоКод','Пройдены все сценарии',done>=3],['🔥','Без лишнего риска','Серия из 5 безопасных решений',state.streak>=5]];const wrap=$('badges');wrap.replaceChildren();badges.forEach(b=>{const x=document.createElement('article');x.className='badge'+(b[3]?'':' locked');const m=document.createElement('div');m.className='medal';m.textContent=b[0];const t=document.createElement('strong');t.textContent=b[1];const d=document.createElement('span');d.textContent=b[2];x.append(m,t,d);wrap.append(x)})}
function reset(){if(!window.confirm('Сбросить имя и игровой прогресс на этом устройстве?'))return;try{localStorage.removeItem(KEY)}catch(e){}location.reload()}
function bind(){document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();view(v.dataset.view)}const a=e.target.closest('[data-action]');if(a){e.preventDefault();if(a.dataset.action==='start'){view('sim');setTimeout(()=>start(scenarios.find(s=>!state.done[s.id])?.id||scenarios[0].id),120)}else if(a.dataset.action==='how'){document.querySelector('#view-home .section').scrollIntoView({behavior:'smooth'})}else if(a.dataset.action==='profile')openProfile();else if(a.dataset.action==='reset')reset()}});$('profileBtn').addEventListener('click',openProfile);$('closeModal').addEventListener('click',closeProfile);$('saveName').addEventListener('click',saveProfile);$('nameInput').addEventListener('keydown',e=>{if(e.key==='Enter')saveProfile()});$('profileModal').addEventListener('click',e=>{if(e.target===$('profileModal'))closeProfile()});$('spotBag').addEventListener('click',()=>inspect('bag'));$('spotFire').addEventListener('click',()=>inspect('fire'));$('spotSky').addEventListener('click',()=>inspect('sky'));$('waterBtn').addEventListener('click',()=>mini('water'));$('adultBtn').addEventListener('click',()=>mini('adult'));$('callBtn').addEventListener('click',()=>mini('call'));$('replayBtn').addEventListener('click',()=>{if(current)start(current.id)});$('backBtn').addEventListener('click',()=>{$('game').hidden=true;$('questionBox').style.display='block';$('result').classList.remove('show');view('sim')})}
load();bind();updateHeader();renderScenarios();renderProgress();if(!state.name)setTimeout(openProfile,500);
