(() => {
  'use strict';
  const missions = [
    {id:'camp', title:'Нулевая искра', meta:'ПОХОД · СТОЯНКА', icon:'⛺', intro:'Три сигнала. Одно решение. Сначала исследуй место, затем действуй.', clues:['Сухая трава подходит к зоне огня.','Порывы ветра усиливаются.','На въезде указано ограничение на открытый огонь.'], rounds:[
      ['Первые минуты','Друзья уже достают спички. Условия никто не проверял.',[['Остановить подготовку и проверить место, ветер и ограничения',12],['Поторопиться поставить костёр',-12],['Выбрать самый сухой участок',-16]]],
      ['Ветер усилился','Друг говорит: «Огонь маленький, ничего не случится».', [['Изменить план: при таких условиях открытый огонь не нужен',14],['Оставить всё как есть',-14],['Попробовать быстро',-16]]],
      ['Ограничение','Компания спорит, можно ли обойти запрет маленьким огнём.',[['Отказаться от открытого огня',16],['Сделать огонь меньше',-18],['Проверить, часто ли здесь проверяют',-12]]],
      ['Дым','Между деревьями появляется дым, но пламени не видно.',[['Не приближаться, предупредить взрослого и сообщить 101/112',18],['Пойти посмотреть ближе',-20],['Подождать, пока станет очевиднее',-15]]],
      ['Финал','Кто-то говорит: «Раз пламени не видно, всё нормально».',[['Оставить место безопасным и не приближаться к дыму',18],['Сначала забрать все вещи',-8],['Решить голосованием',-10]]]
    ]},
    {id:'storm', title:'Перехват погоды', meta:'ТУНДРА · РЫБАЛКА', icon:'◒', intro:'Погода меняется. Побеждает тот, кто вовремя меняет план.', clues:['В прогнозе предупреждение о сильном ветре.','Порывы над водой становятся резкими.','В рюкзаке предлагают горючую жидкость для розжига.'], rounds:[
      ['Прогноз','До выхода выбираем данные, которые реально влияют на безопасность.',[['Проверить предупреждения, ветер, осадки и ограничения',12],['Посмотреть только температуру',-8],['Ориентироваться только на время',-8]]],
      ['Снаряжение','Кто-то предлагает горючую жидкость «на всякий случай».',[['Отказаться и выбрать безопасный формат отдыха',15],['Взять немного',-16],['Проверить свойства экспериментом',-20]]],
      ['Перелом','Через час ветер стал значительно сильнее.',[['Признать, что план больше не подходит, и изменить его',16],['Продолжить, ведь всё уже готово',-14],['Спросить, кто готов рискнуть',-15]]],
      ['Дым','На горизонте появляется дым неизвестного происхождения.',[['Остаться на расстоянии, предупредить взрослого и сообщить',18],['Пойти к дыму',-19],['Сначала снять видео',-15]]],
      ['Код маршрута','Что переносится из игры в любую поездку?',[['Сначала условия и последствия, потом действие',18],['Если раньше получилось, получится снова',-10],['План нельзя менять',-12]]]
    ]},
    {id:'picnic', title:'Смена сценария', meta:'ПИКНИК · КОМАНДА', icon:'▱', intro:'Здесь нужно не только заметить риск, но и изменить решение группы.', clues:['Сухая трава и низкие ветви рядом.','Кто-то говорит: «Мы всегда здесь так делаем».','Младшие дети бегают рядом с зоной отдыха.'], rounds:[
      ['Разговор','Семья обсуждает, где поставить источник огня.',[['Сначала проверить правила, место и условия',11],['Выбрать самое красивое место',-8],['Попросить самого смелого решить',-9]]],
      ['Место','Рядом сухая трава и низкие ветви.',[['При таких условиях отказаться от открытого огня',16],['Согласиться, если огонь маленький',-16],['Согласиться, если рядом взрослый',-12]]],
      ['Люди','Дети бегают между вещами, взрослые заняты едой.',[['Попросить взрослого организовать безопасную зону',14],['Назначить ребёнка ответственным за огонь',-20],['Ничего не менять',-14]]],
      ['Диалог','Родственник не хочет менять привычный отдых.',[['Объяснить конкретный риск и предложить безопасный вариант',17],['Сказать: «Потому что я решил»',-7],['Промолчать',-12]]],
      ['Капитан','Группа теперь смотрит на ситуацию твоими глазами.',[['Замечать изменение условий и вовремя менять решение',18],['Никогда не отдыхать у костра',-6],['Всегда делать только то, что говорит старший',-8]]]
    ]}
  ];
  const store = 'ecocode_game_v4';
  let data = {xp:0,done:[],best:0,badges:[]};
  try { data = Object.assign(data, JSON.parse(localStorage.getItem(store) || '{}')); } catch (_) {}
  const $ = (s,r=document) => r.querySelector(s);
  const esc = x => String(x).replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  function save(){ try{localStorage.setItem(store,JSON.stringify(data));}catch(_){} }
  function show(id){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+id)); document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); window.scrollTo({top:0,behavior:'smooth'}); if(id==='sim') renderList(); if(id==='progress') renderProgress(); }
  function renderList(){ const box=$('#scenarioList'); if(!box)return; box.innerHTML=''; missions.forEach((m,i)=>{const unlocked=i===0||data.done.includes(missions[i-1].id);const b=document.createElement('button');b.type='button';b.className='scenario-card'+(unlocked?'':' locked');b.disabled=!unlocked;b.innerHTML='<span class="sc-icon">'+m.icon+'</span><span><span class="sc-title">'+m.title+'</span><span class="sc-desc">'+m.intro+'</span><span class="sc-meta">'+m.meta+' · 5 этапов · 3 сигнала</span></span><span class="status '+(data.done.includes(m.id)?'done':'open')+'">'+(data.done.includes(m.id)?'пройдено':unlocked?'доступно':'закрыто')+'</span>';b.onclick=()=>start(m);box.appendChild(b);}); const t=$('#overallProgressText');const p=$('#overallProgressBar');if(t)t.textContent=data.done.length+' / 3';if(p)p.style.width=(data.done.length/3*100)+'%'; }
  function start(m){ const game=$('#game'); if(!game)return; let round=0,found=0,score=0,risk=18,streak=0,bestStreak=0; game.hidden=false; game.classList.add('eco-v3'); const draw=()=>{game.innerHTML='<div class="mission-hud"><div><div class="mission-sub">Миссия · '+m.meta+'</div><div class="mission-title">'+m.title+'</div></div><div class="hud-right"><span class="chip">✦ <b>'+data.xp+'</b> XP</span><span class="chip">🔥 <b>'+bestStreak+'</b></span></div></div><div class="intel"><div class="intel-title"><span>Разведданные</span><span>'+found+' / 3</span></div><div class="intel-track">'+m.clues.map((c,i)=>'<button class="intel-dot '+(i<found?'found':'')+'" data-clue="'+i+'">'+(i<found?'✓ ':'')+(i+1)+' · '+esc(i<found?c:'Сигнал закрыт')+'</button>').join('')+'</div></div><div class="mission-stage"><div class="world '+(m.id==='storm'?'storm':m.id==='picnic'?'picnic':'sun')+'"><div class="sun"></div><div class="mountain m1"></div><div class="mountain m2"></div><div class="trees"></div><div class="ground"></div><div class="tent"></div><div class="fire"></div><div class="person"></div><div class="rain"></div><div class="wind-lines"></div></div><div class="riskbar"><label><span>ЭКОРИСК</span><span id="v4risk">'+(risk<30?'низкий':risk<60?'контролируемый':'высокий')+'</span></label><div class="riskline"><i style="width:'+risk+'%"></i></div></div><div class="scan-panel" id="scan"></div><div class="decision" id="decision"></div></div>'; scan();};
    const scan=()=>{const p=$('#scan');p.innerHTML='<div class="scan-kicker">ШАГ 1 · РАЗВЕДКА</div><div class="scan-title">Собери три сигнала</div><div class="scan-copy">Нажимай на сигналы по порядку. Сначала наблюдение, потом решение.</div><div class="scan-grid">'+m.clues.map((c,i)=>'<button class="scan-btn" data-clue="'+i+'"><small>СИГНАЛ '+(i+1)+'</small><b>'+esc(i<found?c:'Проверить')+'</b></button>').join('')+'</div>';p.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>{const i=+b.dataset.clue;if(i!==found)return;found++;risk=Math.max(7,risk+(i===1?4:-2));drawScanOnly();if(found===3)decision();});$('#decision').innerHTML='<div class="phase">РАЗВЕДКА</div><h3>Осмотри ситуацию</h3><p>Открывай сигналы по очереди. Они нужны, чтобы решение не было угадайкой.</p>';};
    const drawScanOnly=()=>{const p=$('#scan');if(!p)return; p.querySelectorAll('[data-clue]').forEach(b=>{const i=+b.dataset.clue;b.disabled=i<found;if(i<found)b.classList.add('found');});p.querySelector('.scan-title').textContent=found===3?'Картина собрана':'Сигнал найден';p.querySelector('.scan-copy').textContent=found===3?'Теперь решение строится на трёх фактах.':'Ищи следующий сигнал.';};
    const decision=()=>{const r=m.rounds[round];$('#decision').innerHTML='<div class="phase">ЭТАП '+(round+1)+' / '+m.rounds.length+' · '+r[0]+'</div><h3>'+esc(r[1])+'</h3><div class="choice-grid">'+r[2].map((c,i)=>'<button class="choice" data-choice="'+i+'"><span class="num">ВАРИАНТ '+(i+1)+'</span>'+esc(c[0])+'</button>').join('')+'</div><div class="outcome" id="outcome"></div><button class="btn primary next" id="nextV4">Продолжить миссию →</button>';$('#nextV4').style.display='none';$('#decision').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(+b.dataset.choice));};
    const choose=i=>{const c=m.rounds[round][2][i];score+=c[1];if(c[1]>0){risk=Math.max(5,risk-10);streak++;bestStreak=Math.max(bestStreak,streak);data.xp+=c[1]}else{risk=Math.min(96,risk+Math.abs(c[1]));streak=0;data.xp+=2}save();const out=$('#outcome');out.className='outcome show '+(c[1]>0?'good':'bad');out.innerHTML='<strong>'+(c[1]>0?'✓ Хорошее решение':'⚠ Последствие')+'</strong> — '+esc(c[0]);$('#decision').querySelectorAll('.choice').forEach(b=>b.disabled=true);$('#nextV4').style.display='inline-flex';$('#nextV4').onclick=()=>{round++;found=0;if(round>=m.rounds.length){finish();}else{draw();}};};
    const finish=()=>{if(!data.done.includes(m.id))data.done.push(m.id);data.best=Math.max(data.best,bestStreak);if(found===0){}if(!data.badges.includes('Разведчик'))data.badges.push('Разведчик');if(bestStreak>=3&&!data.badges.includes('Серия решений'))data.badges.push('Серия решений');save();game.innerHTML='<div class="mission-stage"><div class="finish"><div class="finish-card"><div class="finish-medal">✦</div><div class="eyebrow">Миссия завершена</div><h2>'+(score>=60?'Сильный результат':'Миссия пройдена')+'</h2><p>Ты исследовал ситуацию и принимал решения с учётом изменяющихся условий.</p><div class="score-grid"><div class="score-box"><b>'+score+'</b><span>очки</span></div><div class="score-box"><b>'+risk+'</b><span>экориск</span></div><div class="score-box"><b>'+bestStreak+'</b><span>серия</span></div><div class="score-box"><b>3/3</b><span>разведка</span></div></div><div class="finish-actions"><button class="btn primary" id="again">↻ Повторить</button><button class="btn secondary" id="back">К миссиям</button></div></div></div></div>';$('#again').onclick=()=>start(m);$('#back').onclick=()=>{game.hidden=true;show('sim');};renderList();renderProgress();};
    draw();
  }
  function renderProgress(){const a=$('#totalXP'),b=$('#doneCount'),c=$('#safeStreak'),d=$('#badges');if(a)a.textContent=data.xp+' XP';if(b)b.textContent=data.done.length+' / 3';if(c)c.textContent=data.best;if(d)d.innerHTML=data.badges.map(x=>'<article class="card"><div class="card-icon">✦</div><h3>'+esc(x)+'</h3><p>Достижение за игровые действия.</p></article>').join('')||'<article class="card"><h3>Пока пусто</h3><p>Пройди первую миссию.</p></article>';}
  function boot(){ document.querySelectorAll('[data-view]').forEach(b=>{if(b.tagName==='BUTTON'||b.tagName==='A')b.addEventListener('click',ev=>{const id=b.dataset.view;if(id){ev.preventDefault();show(id);}})});document.querySelectorAll('[data-action="start"]').forEach(b=>b.addEventListener('click',()=>show('sim')));document.querySelectorAll('[data-action="how"]').forEach(b=>b.addEventListener('click',()=>alert('ЭкоКод — это миссия: сначала разведка, затем решение, затем последствие. Ошибки повышают экориск, а безопасные решения дают XP.')));renderList();renderProgress();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();