'use strict';
(()=>{
const STORE='ecocode_game_v3';
const NEWS=[
{tag:'ЯНАО',date:'4 сентября 2026',title:'Лесопожарная обстановка остаётся под контролем',text:'Рослесхоз сообщил, что 3 сентября лесные пожары ликвидировали в том числе в ЯНАО. За сутки по России ликвидировали 29 пожаров на площади 74 041 га.',source:'Рослесхоз',url:'https://rosleshoz.gov.ru/activity/forest-security-and-protection/fires/operative-information/?PAGEN_24=3'},
{tag:'ЯНАО',date:'2 сентября 2026',title:'Лесопожарную ситуацию в округе держат на контроле',text:'Глава Рослесхоза посетил ЯНАО. Ведомство сообщило, что лесопожарная обстановка в наиболее горимых регионах находится на контроле.',source:'Рослесхоз',url:'https://rosleshoz.gov.ru/news/federal/ivan-sovetnikov-po-porucheniyu-zampreda-pravitelstva-rossii-dmitriya-patrusheva-lesopozharnaya-obstanovka-v-naibolee-gorimykh-regionakh-nakhoditsya-na-kontrole/'},
{tag:'ПРАВИЛА',date:'28 августа 2026',title:'В ЯНАО действовали режимы ЧС из-за природных пожаров',text:'МЧС ЯНАО сообщало о действующих очагах природных пожаров и режимах чрезвычайной ситуации. Перед поездкой важно проверять официальные ограничения.',source:'МЧС России',url:'https://89.mchs.gov.ru/deyatelnost/press-centr/novosti/5817696'},
{tag:'ОПЕРАТИВНО',date:'31 августа 2026',title:'В Сибири и на Дальнем Востоке сохранялась повышенная пожарная опасность',text:'Рослесхоз отмечал тёплую погоду и повышенные классы пожарной опасности в ряде регионов. Для туриста это означает: проверять актуальную обстановку перед выездом.',source:'Рослесхоз',url:'https://rosleshoz.gov.ru/press/news/'},
{tag:'СИГНАЛ',date:'3 сентября 2026',title:'Оперативные сводки обновляются регулярно',text:'Лесопожарная обстановка меняется быстрее старых памяток. Перед поездкой важно смотреть свежие сообщения ведомств.',source:'Рослесхоз',url:'https://rosleshoz.gov.ru/activity/forest-security-and-protection/fires/operative-information/'}
];
const MISSIONS=[
{id:'camp',icon:'⛺',title:'Нулевая искра',subtitle:'ПОХОД · СТОЯНКА',brief:'Заметь риск раньше остальных и не дай плохому плану стать реальностью.',color:'sun',clues:[['МЕСТО','Сухая трава подходит почти вплотную к предполагаемому месту огня.','Сухая растительность рядом с огнём — тревожный признак.','risk'],['НЕБО','Порывы ветра становятся сильнее. Верхушки деревьев заметно качает.','Ветер увеличивает вероятность распространения огня.','risk'],['ТАБЛИЧКА','У въезда указано действующее ограничение на открытый огонь.','Ограничение меняет сам план отдыха.','rule']],rounds:[
['01 · СТАРТ','Первые две минуты','Друзья уже достают спички. Никто не проверил условия. Что ты делаешь первым?',[['Остановить подготовку и проверить место, погоду и ограничения','good','Ты собираешь данные до действия.',10],['Разделить обязанности и быстрее поставить костёр','bad','Вы ускорили действие, не проверив риск.',-12],['Найти самый сухой участок','bad','Сухая растительность повышает риск.',-15]]],
['02 · КОНФЛИКТ','«Да ладно, огонь маленький»','Ветер усиливается. Друг уверен, что маленький костёр ничего не изменит.',[['Сказать: «Размер огня не отменяет опасных условий. Меняем план»','good','Ты меняешь решение группы вместе с условиями.',12],['Попросить просто не отходить от огня','bad','Наблюдение человека не устраняет опасные условия.',-10],['Попробовать быстро, пока ветер не сильнее','bad','Скорость не компенсирует риск.',-14]]],
['03 · ПРАВИЛО','Ограничение на месте','На табличке указано ограничение на открытый огонь. Компания спорит, можно ли сделать совсем маленький.',[['Отказаться от открытого огня и выбрать другой формат','good','Правило определяет допустимый формат отдыха.',14],['Сделать маленький огонь','bad','Ограничение нельзя обходить размером костра.',-18],['Спросить, часто ли здесь проверяют правило','bad','Проверки не меняют само правило.',-16]]],
['04 · СИГНАЛ','Дым между деревьями','Ты замечаешь дым. Пламени не видно. Что становится главным действием?',[['Не приближаться, предупредить взрослого и сообщить 101/112','good','Безопасность и сообщение важнее любопытства.',16],['Пойти ближе и снять видео','bad','Приближаться к возможному пожару опасно.',-20],['Ждать, пока появится пламя','bad','Не нужно ждать ухудшения ситуации для сообщения.',-17]]],
['05 · ФИНАЛ','Проверка лидера','Компания готова уходить. Кто-то говорит: «Раз пламени не видно, всё нормально».', [['Оставить место без источников огня и не приближаться к дыму','good','Ты сформулировал принцип, а не запомнил фразу.',18],['Главное — забрать еду и рюкзаки','bad','Вещи не являются главным критерием безопасности.',-8],['Решить голосованием','bad','Безопасность не определяется большинством.',-12]]]
]},
{id:'fish',icon:'◒',title:'Перехват погоды',subtitle:'ТУНДРА · РЫБАЛКА',brief:'Погода меняется прямо во время поездки. Побеждает тот, кто вовремя меняет план.',color:'storm',clues:[['ПРОГНОЗ','В прогнозе есть предупреждение и сильные порывы ветра.','Погода — часть оценки пожарного риска.','rule'],['ВОДА','Поверхность воды темнеет, порывы становятся резкими.','Обстановка меняется прямо сейчас.', 'risk'],['СНАРЯЖЕНИЕ','В рюкзаке предлагают горючую жидкость для розжига.','Горючие смеси повышают риск.', 'risk']],rounds:[
['01 · РАЗВЕДКА','План до выезда','До выхода ты смотришь прогноз. Какие данные должны повлиять на решение?',[['Предупреждения, ветер, осадки и ограничения','good','Ты собираешь картину целиком.',10],['Только температуру','bad','Один показатель не описывает обстановку.',-9],['Только время заката','bad','Время суток не заменяет оценку условий.',-8]]],
['02 · СНАРЯЖЕНИЕ','Быстрый розжиг','Кто-то предлагает взять горючую жидкость «на всякий случай».',[['Отказаться и перестроить отдых без опасного розжига','good','Ты убираешь дополнительный риск заранее.',13],['Взять немного','bad','Количество не делает горючую смесь безопасной.',-15],['Проверить свойства на месте','bad','Эксперименты с огнём опасны.',-20]]],
['03 · ПЕРЕЛОМ','Погода изменилась','Через час ветер стал значительно сильнее. Лагерь уже разложен.',[['Признать, что план больше не подходит, и изменить его','good','Адаптация — ключевой навык.',15],['Продолжить, ведь всё подготовлено','bad','Потраченные усилия не меняют условия.',-13],['Спросить, кто готов рискнуть','bad','Готовность рисковать не делает план безопасным.',-15]]],
['04 · ДЫМ','Неизвестный источник','На горизонте появляется дым. Ты не знаешь, насколько далеко источник.',[['Остаться на безопасном расстоянии, предупредить взрослого и сообщить','good','Ты не превращаешь наблюдение в опасное приближение.',17],['Пойти к дыму','bad','К возможному пожару приближаться нельзя.',-18],['Снять видео и отправить друзьям','bad','Сначала безопасность и сообщение.',-16]]],
['05 · ФИНАЛ','Код маршрута','Вы выбираете новый план. Какой принцип переносится на любую поездку?',[['Сначала условия и последствия — потом действие','good','Это логика ЭкоКода.',18],['Если раньше получилось, получится снова','bad','Условия каждый раз могут быть другими.',-10],['Лучший план нельзя менять','bad','Безопасный план должен адаптироваться.',-12]]]
]},
{id:'picnic',icon:'▱',title:'Смена сценария',subtitle:'ПИКНИК · КОМАНДА',brief:'Здесь нужно не только заметить риск, но и убедить других изменить привычный план.',color:'picnic',clues:[['ПОЛЯНА','Сухая трава и низкие ветви рядом с зоной отдыха.','Красивое место не обязательно безопасно для открытого огня.','risk'],['КОМАНДА','Кто-то говорит: «Мы всегда здесь так делаем».','Прошлый опыт не заменяет сегодняшние условия.','social'],['ДЕТИ','Младшие дети бегают между вещами и зоной отдыха.','Безопасное пространство организуют заранее.', 'social']],rounds:[
['01 · КОМАНДА','Первое решение','Семья сразу обсуждает, где поставить мангал. Как изменить разговор?',[['Сначала проверить правила, место и текущие условия','good','Ты переводишь разговор с привычки на оценку риска.',10],['Выбрать самое красивое место','bad','Красивое место не означает безопасное.',-8],['Попросить самого смелого выбрать','bad','Безопасность не зависит от смелости.',-9]]],
['02 · МЕСТО','«Просто отодвинем траву»','Рядом сухая трава и низкие ветви. Предлагают просто убрать траву.',[['При таких условиях отказаться от открытого огня','good','Ты распознаёшь опасную комбинацию факторов.',14],['Согласиться, если огонь маленький','bad','Размер не устраняет риск.',-15],['Согласиться, если рядом взрослый','bad','Взрослый не отменяет ограничения и риск.',-12]]],
['03 · ЛЮДИ','Младшие рядом','Дети бегают между вещами. Взрослые заняты едой.',[['Убрать опасные предметы и попросить взрослого организовать зону','good','Ты не перекладываешь ответственность на ребёнка.',13],['Назначить ребёнка ответственным за огонь','bad','Ребёнок не должен контролировать источник огня.',-20],['Ничего не менять, пока никто не пострадал','bad','Безопасность строится до происшествия.',-14]]],
['04 · ДИАЛОГ','«Не хочу портить отдых»','Родственник раздражён правилами. Нужно изменить решение без конфликта.',[['Объяснить конкретный риск и предложить безопасный формат','good','Конкретные признаки помогают группе принять решение.',17],['Сказать: «Потому что я так решил»','bad','Авторитет без объяснения работает хуже.',-7],['Промолчать','bad','Молчание не устраняет риск.',-13]]],
['05 · ФИНАЛ','Роль капитана','Группа теперь смотрит на ситуацию твоими глазами. Что остаётся?', [['Замечать изменение условий и вовремя менять решение всей группы','good','Навык переносится за пределы игры.',18],['Никогда не отдыхать у костра','bad','Важно оценивать условия и правила, а не просто запрещать всё.',-6],['Всегда делать только то, что говорит старший','bad','Нужно понимать причину решения.',-8]]]
]}
];
const D=()=>({xp:0,completed:[],badges:[],best:0});let state=load(),current=null,round=0,score=0,risk=22,found=0,streak=0,maxStreak=0;
function load(){try{return Object.assign(D(),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return D()}}function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch{}}function q(s,r=document){return r.querySelector(s)}function e(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function news(){const home=q('#view-home');if(!home||q('.eco-news',home))return;const sec=document.createElement('section');sec.className='eco-news section';sec.innerHTML='<div class="eco-news-head"><div><div class="eyebrow">Полевой радар</div><h2>Новости, которые<br>учат замечать риск</h2></div><p class="eco-news-note">Короткие карточки по официальным сообщениям МЧС России и Рослесхоза: факт, контекст и вывод для человека на природе.</p></div><div class="eco-news-grid"></div><div class="eco-principle"><strong>Факт → контекст → действие</strong><span>Дата и первичный источник указаны в каждой карточке.</span></div>';const g=q('.eco-news-grid',sec);NEWS.forEach((n,i)=>{const c=document.createElement('article');c.className='eco-news-card'+(i===0?' feature':'');c.innerHTML=`<div class="eco-news-meta"><b>${e(n.tag)}</b><time>${e(n.date)}</time></div><h3>${e(n.title)}</h3><p>${e(n.text)}</p><a href="${e(n.url)}" target="_blank" rel="noopener noreferrer">Читать первичный источник →</a><span class="eco-news-source">${e(n.source)}</span>`;g.append(c)});home.append(sec)}
function list(){const l=q('#scenarioList');if(!l)return;l.innerHTML='';MISSIONS.forEach((m,i)=>{const unlocked=i===0||state.completed.includes(MISSIONS[i-1].id),done=state.completed.includes(m.id),b=document.createElement('button');b.type='button';b.className='scenario-card'+(!unlocked?' locked':'');b.disabled=!unlocked;b.innerHTML=`<span class="sc-icon">${m.icon}</span><span><span class="sc-title">${e(m.title)}</span><span class="sc-desc">${e(m.brief)}</span><span class="sc-meta">${e(m.subtitle)} · 5 этапов · разведка</span></span><span class="status ${done?'done':'open'}">${done?'пройдено':unlocked?'доступно':'закрыто'}</span>`;b.addEventListener('click',()=>start(m.id));l.append(b)});const t=q('#overallProgressText'),bar=q('#overallProgressBar');if(t)t.textContent=`${state.completed.length} / 3`;if(bar)bar.style.width=`${state.completed.length/3*100}%`}
function start(id){current=MISSIONS.find(m=>m.id===id);if(!current)return;round=0;score=0;risk=22;found=0;streak=0;maxStreak=0;const g=q('#game');g.hidden=false;g.classList.add('eco-v3');g.innerHTML=`<div class="mission-hud"><div><div class="mission-sub">Миссия · ${e(current.subtitle)}</div><div class="mission-title">${e(current.title)}</div></div><div class="hud-right"><span class="chip">✦ <b id="v3xp">${state.xp}</b> XP</span><span class="chip">🔥 <b id="v3streak">0</b></span></div></div><div class="intel"><div class="intel-title"><span>Разведданные</span><span id="intelCount">0 / 3</span></div><div class="intel-track">${current.clues.map((c,i)=>`<div class="intel-dot" id="intel-${i}">${i+1} · ${e(c[0])}</div>`).join('')}</div></div><div class="mission-stage"><div class="world ${current.color}"><div class="sun"></div><div class="mountain m1"></div><div class="mountain m2"></div><div class="trees"></div><div class="ground"></div><div class="tent"></div><div class="fire"></div><div class="person"></div><div class="rain"></div><div class="wind-lines"></div></div><div class="riskbar"><label><span>ЭКОРИСК</span><span id="v3riskLabel">низкий</span></label><div class="riskline"><i id="v3risk"></i></div></div><div class="scan-panel" id="scanPanel"></div><div class="decision" id="decision"></div></div>`;q('#scenarioList').style.display='none';scan();g.scrollIntoView({behavior:'smooth',block:'start'})}
function scan(){const p=q('#scanPanel');p.innerHTML=`<div class="scan-kicker">ШАГ 1 · РАЗВЕДКА</div><div class="scan-title">Собери картину до решения</div><div class="scan-copy">Исследуй три объекта. Улики открываются по порядку — сначала наблюдение, потом вывод.</div><div class="scan-grid">${current.clues.map((c,i)=>`<button class="scan-btn" data-clue="${i}" type="button"><small>${i+1}</small><b>${e(c[0])}</b></button>`).join('')}</div>`;p.querySelectorAll('[data-clue]').forEach(b=>b.addEventListener('click',()=>clue(+b.dataset.clue)));q('#decision').innerHTML='<div class="phase">ПОЛЕВАЯ ПРОВЕРКА</div><h3>Сначала осмотри место</h3><p>Пока не собраны все три сигнала, ты не видишь всей ситуации.</p>'}
function clue(i){if(i!==found)return;const c=current.clues[i];found++;risk=Math.max(8,risk+(c[3]==='risk'?4:-2));q(`#intel-${i}`).classList.add('found');q(`#intel-${i}`).innerHTML=`✓ ${e(c[0])}: ${e(c[2])}`;q('#intelCount').textContent=`${found} / 3`;q(`#scanPanel [data-clue="${i}"]`).classList.add('found');if(found===3)decision();else toast(`Улика найдена · ${c[2]}`)}
function decision(){const r=current.rounds[round],p=q('#scanPanel');p.innerHTML='<div class="scan-kicker">РАЗВЕДКА ЗАВЕРШЕНА · 3/3</div><div class="scan-title">Картина собрана</div><div class="scan-copy">Теперь решение строится на трёх сигналах, а не на интуиции.</div>';q('#decision').innerHTML=`<div class="phase">${e(r[0])} · ЭТАП ${round+1} / ${current.rounds.length}</div><h3>${e(r[1])}</h3><p>${e(r[2])}</p><div class="choice-grid">${r[3].map((c,i)=>`<button class="choice" data-choice="${i}" type="button"><span class="num">ВАРИАНТ ${i+1}</span>${e(c[0])}</button>`).join('')}</div><div class="outcome" id="outcome"></div><button class="btn primary next" id="nextV3" type="button">Продолжить миссию →</button>`;q('#decision').querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.choice)));riskUI()}
function choose(i){const r=current.rounds[round],c=r[3][i],good=c[1]==='good';score+=c[3];if(good){risk=Math.max(5,risk-12);streak++;maxStreak=Math.max(maxStreak,streak);state.xp+=c[3]}else{risk=Math.min(96,risk+Math.abs(c[3]));streak=0;state.xp+=2}save();q('#v3xp').textContent=state.xp;q('#v3streak').textContent=streak;q('#outcome').className=`outcome show ${good?'good':'bad'}`;q('#outcome').innerHTML=`<strong>${good?'✓ Решение сработало':'⚠ Последствие'}</strong> — ${e(c[2])}`;q('#decision').querySelectorAll('.choice').forEach(b=>b.disabled=true);q('#nextV3').classList.add('show');riskUI()}
function next(){round++;if(round>=current.rounds.length)finish();else decision()}
function riskUI(){const i=q('#v3risk');if(i)i.style.width=`${risk}%`;const l=q('#v3riskLabel');if(l){l.textContent=risk<30?'низкий':risk<60?'контролируемый':risk<80?'высокий':'критический';l.style.color=risk<30?'#d3ff82':risk<60?'#ffc36b':'#ff7166'}}
function finish(){const grade=score>=60?'НАБЛЮДАТЕЛЬ':score>=30?'НАДЁЖНЫЙ ТУРИСТ':'ЕСТЬ ЧТО ПРОКАЧАТЬ';if(!state.completed.includes(current.id))state.completed.push(current.id);state.best=Math.max(state.best,maxStreak);if(found===3&&!state.badges.includes('Разведчик'))state.badges.push('Разведчик');if(maxStreak>=3&&!state.badges.includes('Серия решений'))state.badges.push('Серия решений');if(score>=60&&!state.badges.includes('Хладнокровие'))state.badges.push('Хладнокровие');save();q('#decision').outerHTML=`<div class="finish"><div class="finish-card"><div class="finish-medal">✦</div><div class="eyebrow">Миссия завершена</div><h2>${grade}</h2><p>${score>=60?'Ты собирал данные, замечал изменения и менял план — именно этот навык переносится из игры в реальную поездку.':'Миссия пройдена. Повтори её и попробуй снизить экориск, сохранив внимательность.'}</p><div class="score-grid"><div class="score-box"><b>${score}</b><span>очки решения</span></div><div class="score-box"><b>${risk}</b><span>финальный риск</span></div><div class="score-box"><b>${maxStreak}</b><span>серия</span></div><div class="score-box"><b>${found}/3</b><span>разведка</span></div></div><div class="finish-actions"><button class="btn primary" id="againV3">↻ Пройти снова</button><button class="btn secondary" id="missionsV3">К сценариям</button></div></div></div>`;q('#againV3').addEventListener('click',()=>start(current.id));q('#missionsV3').addEventListener('click',()=>{q('#game').hidden=true;q('#scenarioList').style.display='grid';list()});list();progress()}
function toast(text){const old=q('.toast-v3');if(old)old.remove();const t=document.createElement('div');t.className='toast-v3';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),2200)}
function progress(){const a=q('#totalXP'),b=q('#doneCount'),c=q('#safeStreak'),d=q('#badges');if(a)a.textContent=`${state.xp} XP`;if(b)b.textContent=`${state.completed.length} / 3`;if(c)c.textContent=state.best;if(d)d.innerHTML=state.badges.length?state.badges.map(x=>`<article class="card"><div class="card-icon">✦</div><h3>${e(x)}</h3><p>Получено за игровые действия.</p></article>`).join(''):'<article class="card"><h3>Пока пусто</h3><p>Пройди миссию и собери первое достижение.</p></article>'}
function boot(){news();list();progress();document.querySelectorAll('[data-action="start"]').forEach(b=>b.addEventListener('click',()=>{const n=q('[data-view="sim"]');if(n)n.click();setTimeout(()=>{list();const f=q('#scenarioList [data-mission]')||q('#scenarioList button');if(f&&!f.disabled)f.click()},80)}));const g=q('#game');if(g)g.addEventListener('click',ev=>{if(ev.target.id==='nextV3')next()});const top=q('.teacher-toolbar a[href="#teacher-feedback"]');if(top)top.remove();const fb=q('#teacherFeedbackLink');if(fb){fb.textContent='Открыть форму обратной связи →';fb.classList.add('primary');fb.classList.remove('secondary')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();